tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "ngrok/ngrok"
brew "zstd"
brew "awscli"
brew "colordiff"
# brew "ruby"
# brew "cocoapods"
# brew "libpq"
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "gitmoji"
brew "git-secrets"
brew "imagemagick"
brew "mysql"
brew "neovim"
brew "peco"
brew "postgresql", restart_service: true
brew "sheldon"
brew "starship"
brew "ruby-build"
brew "rbenv"
brew "redis", restart_service: true
brew "rename"
brew "mise"
brew "tmux"
brew "tree"
brew "yarn"
cask "arc"
cask "chromedriver"
cask "git-credential-manager"
cask "ngrok"
cask "pgadmin4"
cask "postman"
cask "setapp"
brew "watchman"
brew "wget"
brew "mackerelio/mackerel-agent/mkr"
brew "peco"
vscode "adpyke.codesnap"
vscode "adpyke.vscode-sql-formatter"
# vscode "aeschli.vscode-css-formatter"
vscode "ahebrank.yaml2json"
# vscode "aki77.rails-db-schema"
# vscode "aki77.rails-routes"
# vscode "Arjun.swagger-viewer"
vscode "bierner.markdown-mermaid"
vscode "bpruitt-goddard.mermaid-markdown-syntax-highlighting"
vscode "bradlc.vscode-tailwindcss"
vscode "bung87.rails"
vscode "bung87.vscode-gemfile"
# vscode "castwide.solargraph"
# vscode "christian-kohler.npm-intellisense"
vscode "CraigMaslowski.erb"
# vscode "csstools.postcss"
# vscode "Dart-Code.dart-code"
# vscode "Dart-Code.flutter"
vscode "DavidAnson.vscode-markdownlint"
# vscode "dbaeumer.vscode-eslint"
# vscode "DigitalBrainstem.javascript-ejs-support"
vscode "donjayamanne.githistory"
vscode "DotJoshJohnson.xml"
# vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "EditorConfig.EditorConfig"
vscode "esbenp.prettier-vscode"
vscode "fabiospampinato.vscode-todo-plus"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-complete-tag"
vscode "formulahendry.auto-rename-tag"
vscode "formulahendry.code-runner"
vscode "foxundermoon.next-js"
vscode "foxundermoon.shell-format"
# vscode "github.vscode-github-actions"
vscode "GitHub.vscode-pull-request-github"
# vscode "golang.go"
vscode "groksrc.ruby"
vscode "Gruntfuggly.todo-tree"
vscode "Hridoy.rails-snippets"
vscode "jduponchelle.rainbow-end"
vscode "kaiwood.endwise"
vscode "karunamurti.haml"
vscode "Kelvin.vscode-sshfs"
vscode "khaeransori.json2csv"
# vscode "leizongmin.node-module-intellisense"
vscode "letmaik.git-tree-compare"
vscode "mechatroner.rainbow-csv"
vscode "mhutchie.git-graph"
vscode "mike-co.import-sorter"
vscode "mikestead.dotenv"
# vscode "misogi.ruby-rubocop"
vscode "mquandalle.graphql"
# vscode "mrmlnc.vscode-duplicate"
# vscode "ms-azuretools.vscode-docker"
vscode "MS-CEINTL.vscode-language-pack-ja"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "msjsdiag.vscode-react-native"
vscode "NuclleaR.vscode-extension-auto-import"
vscode "oderwat.indent-rainbow"
# vscode "onecentlin.laravel-blade"
vscode "oouo-diogo-perdigao.docthis"
# vscode "Orta.vscode-jest"
vscode "pavlitsky.yard"
vscode "peakchen90.open-html-in-browser"
vscode "phplasma.csv-to-table"
vscode "planbcoding.vscode-react-refactor"
vscode "pmneo.tsimporter"
vscode "PulkitGangwar.nextjs-snippets"
vscode "rebornix.ruby"
vscode "redhat.java"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.LiveServer"
vscode "robert-brunhage.flutter-riverpod-snippets"
vscode "ryu1kn.partial-diff"
vscode "seatonjiang.gitmoji-vscode"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "sianglim.slim"
vscode "sohamkamani.code-eol"
vscode "steoates.autoimport"
vscode "stringham.move-ts"
vscode "tomoyukim.vscode-mermaid-editor"
vscode "unifiedjs.vscode-remark"
vscode "vayan.haml"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "vscode-icons-team.vscode-icons"
# vscode "Vue.volar"
vscode "wingrunr21.vscode-ruby"
vscode "yzane.markdown-pdf"
vscode "ZainChen.json"
